name: Deploy Wekan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MONGODB_VERSION: 4.4
  WEKAN_VERSION: latest
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and push MongoDB
        run: |
          docker pull mongo:${MONGODB_VERSION}
          docker tag mongo:${MONGODB_VERSION} ${{ env.REGISTRY }}/${{ github.repository }}/mongodb:${MONGODB_VERSION}
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/mongodb:${MONGODB_VERSION}

      - name: Pull and push Wekan
        run: |
          docker pull quay.io/wekan/wekan:${WEKAN_VERSION}
          docker tag quay.io/wekan/wekan:${WEKAN_VERSION} ${{ env.REGISTRY }}/${{ github.repository }}/wekan:${WEKAN_VERSION}
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/wekan:${WEKAN_VERSION}

      - name: Deploy
        run: |
          docker network create wekan-network || true
          
          docker run -d --name mongodb \
            --network wekan-network \
            -v mongodb-data:/data/db \
            -e MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_ROOT_USER }} \
            -e MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }} \
            ${{ env.REGISTRY }}/${{ github.repository }}/mongodb:${MONGODB_VERSION}
          
          docker run -d --name wekan \
            --network wekan-network \
            -e MONGO_URL="mongodb://${{ secrets.MONGO_ROOT_USER }}:${{ secrets.MONGO_ROOT_PASSWORD }}@mongodb:27017/wekan" \
            -e ROOT_URL="${{ secrets.WEKAN_ROOT_URL }}" \
            -e PORT=8080 \
            -p 8080:8080 \
            ${{ env.REGISTRY }}/${{ github.repository }}/wekan:${WEKAN_VERSION}
